### ISSUE TITLE
Game info/liks

### ISSUE THREAD

**Issue by florianKProjects** [noy5277/Card-Game-App#6]

**Comment by florianKProjects** [comment]
Class Diagram:
https://miro.com/app/board/o9J_lxucORM=/
Animation pictures:
https://www.vectorstock.com/royalty-free-vectors/trivia-cartoon-vectors-page_2
https://pixabay.com/images/search/trivia/
https://www.shutterstock.com/search/trivia
https://www.freepik.com/search?dates=any&format=search&page=1&query=trivia&sort=popular
https://stock.adobe.com/
App games:
https://play.google.com/store/apps/details?id=com.etermax.preguntados.lite
https://www.androidsis.com/en/trivia-games-for-two/
https://play.google.com/store/apps/category/GAME_TRIVIA
https://play.google.com/store/apps/details?id=smartowlapps.com.quiz360
https://apkpure.com/trivia-star-free-trivia-games-offline-app/com.trivia.star.android
https://www.vodytech.com/best-trivia-quiz-games-for-android/
https://github.com/sromku/memory-game
https://codecanyon.net/item/online-word-quiz-image-guess-puzzle-game-for-android/23065466
https://androidbooth.com/guess-the-picture-trivia-mix-photo-puzzle-game-android/

**Comment by noy5277** [comment]
Copied to Wiki
